export const GAME_STATUS = {
  GAME_LOCKED: 'GAME_LOCKED',
  GAME_UNLOCKED: 'GAME_UNLOCKED',
  GAME_FIRST_LOAD: 'GAME_FIRST_LOAD',
  GAME_COMPLETED: 'GAME_COMPLETED',
  GAME_SHUFFLED: 'GAME_SHUFFLED',
};
