import { IGameState } from './interfaces';

import {
  FaAccessibleIcon,
  FaAngrycreative,
  FaCcVisa,
  FaDev,
  FaBandcamp,
  FaCodiepie,
  FaCriticalRole,
  FaDeviantart,
  FaDropbox,
  FaDrupal,
  FaFacebookF,
  FaFontAwesomeFlag,
  FaGitkraken,
  FaHtml5,
  FaJava,
  FaPython,
  FaSkype,
  FaSuse
} from 'react-icons/fa';

export const initialGameState: IGameState[] = [
  {id: 1, correspondingId: 36, icon: FaAccessibleIcon, isHidden: false, isRemoved: false},
  {id: 2, correspondingId: 35, icon: FaAngrycreative, isHidden: false, isRemoved: false},
  {id: 3, correspondingId: 34, icon: FaCcVisa, isHidden: false, isRemoved: false},
  {id: 4, correspondingId: 33, icon: FaDev, isHidden: false, isRemoved: false},
  {id: 5, correspondingId: 32, icon: FaBandcamp, isHidden: false, isRemoved: false},
  {id: 6, correspondingId: 31, icon: FaCodiepie, isHidden: false, isRemoved: false},
  {id: 7, correspondingId: 30, icon: FaCriticalRole, isHidden: false, isRemoved: false},
  {id: 8, correspondingId: 29, icon: FaDeviantart, isHidden: false, isRemoved: false},
  {id: 9, correspondingId: 28, icon: FaDropbox, isHidden: false, isRemoved: false},
  {id: 10, correspondingId: 27, icon: FaDrupal, isHidden: false, isRemoved: false},
  {id: 11, correspondingId: 26, icon: FaFacebookF, isHidden: false, isRemoved: false},
  {id: 12, correspondingId: 25, icon: FaFontAwesomeFlag, isHidden: false, isRemoved: false},
  {id: 13, correspondingId: 24, icon: FaGitkraken, isHidden: false, isRemoved: false},
  {id: 14, correspondingId: 23, icon: FaHtml5, isHidden: false, isRemoved: false},
  {id: 15, correspondingId: 22, icon: FaJava, isHidden: false, isRemoved: false},
  {id: 16, correspondingId: 21, icon: FaPython, isHidden: false, isRemoved: false},
  {id: 17, correspondingId: 20, icon: FaSkype, isHidden: false, isRemoved: false},
  {id: 18, correspondingId: 19, icon: FaSuse, isHidden: false, isRemoved: false},
  {id: 19, correspondingId: 18, icon: FaSuse, isHidden: false, isRemoved: false},
  {id: 20, correspondingId: 17, icon: FaSkype, isHidden: false, isRemoved: false},
  {id: 21, correspondingId: 16, icon: FaPython, isHidden: false, isRemoved: false},
  {id: 22, correspondingId: 15, icon: FaJava, isHidden: false, isRemoved: false},
  {id: 23, correspondingId: 14, icon: FaHtml5, isHidden: false, isRemoved: false},
  {id: 24, correspondingId: 13, icon: FaGitkraken, isHidden: false, isRemoved: false},
  {id: 25, correspondingId: 12, icon: FaFontAwesomeFlag, isHidden: false, isRemoved: false},
  {id: 26, correspondingId: 11, icon: FaFacebookF, isHidden: false, isRemoved: false},
  {id: 27, correspondingId: 10, icon: FaDrupal, isHidden: false, isRemoved: false},
  {id: 28, correspondingId: 9, icon: FaDropbox, isHidden: false, isRemoved: false},
  {id: 29, correspondingId: 8, icon: FaDeviantart, isHidden: false, isRemoved: false},
  {id: 30, correspondingId: 7, icon: FaCriticalRole, isHidden: false, isRemoved: false},
  {id: 31, correspondingId: 6, icon: FaCodiepie, isHidden: false, isRemoved: false},
  {id: 32, correspondingId: 5, icon: FaBandcamp, isHidden: false, isRemoved: false},
  {id: 33, correspondingId: 4, icon: FaDev, isHidden: false, isRemoved: false},
  {id: 34, correspondingId: 3, icon: FaCcVisa, isHidden: false, isRemoved: false},
  {id: 35, correspondingId: 2, icon: FaAngrycreative, isHidden: false, isRemoved: false},
  {id: 36, correspondingId: 1, icon: FaAccessibleIcon, isHidden: false, isRemoved: false},
]
